manifest:
  version: 1.2
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr.git
      revision: 413b789deb391d3a37d06b463288a5fe765ee57e # v4.2.0
      path: zephyr
      import:
        name-allowlist:
          - hal_stm32
          - cmsis_6
      west-commands: scripts/west-commands.yml
    - name: mcuboot
      revision: d5b0dcb9aaee397fc105ae2228e8030038c3d871
      path: bootloader/mcuboot
      url: https://github.com/mcu-tools/mcuboot.git
      groups:
       - bootloader
    - name: libcsp
      url: https://github.com/libcsp/libcsp.git
      revision: f8c366e5dfd9879990747d815ff5b2c2dda4dfe3
      path: modules/lib/libcsp
