manifest:
  version: 1.2
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr.git
      revision: 684c9e8f32e4373a21098559f748f06915f950c9 # v4.4.0
      path: zephyr
      import:
        name-allowlist:
          - hal_stm32
          - cmsis_6
      west-commands: scripts/west-commands.yml
    - name: libcsp
      url: https://github.com/libcsp/libcsp.git
      # not a stable revision; run git blame and git show for justification
      revision: 65bc556f7bd658d17833d689b3023e4c03c9165e
      path: modules/lib/libcsp
