manifest:
  version: 1.2
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr.git
      revision: 3568e1b6d5cdd51a6b964a2a1d6d29200fea2056 # v4.3.0
      path: zephyr
      import:
        name-allowlist:
          - hal_stm32
          - cmsis_6
      west-commands: scripts/west-commands.yml
    - name: libcsp
      url: https://github.com/libcsp/libcsp.git
      revision: f8c366e5dfd9879990747d815ff5b2c2dda4dfe3
      path: modules/lib/libcsp
