name: Build Docker Image

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'Dockerfile'
      - 'west.yml'
      - 'scripts/install_dependencies.sh'
      - 'scripts/setup_python_venv.sh'
      - 'scripts/setup_west_workspace.sh'

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t finch-image .

      - name: Run container
        run: docker run -di --name finch-container finch-image sleep infinity

      - name: west build
        run: docker exec finch-container /bin/bash -c "source /env-setup.sh && west build -p -b native_sim/native/64 /zephyr/samples/basic/blinky"
