name: DNM check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
      - edited

permissions:
  contents: read
  pull-requests: read

jobs:
  dnm-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        run: |
          pip install PyGithub

      - name: Run DNM label check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./scripts/dnm.py
          ./scripts/dnm.py -p ${{ github.event.pull_request.number }}
